export default {
  getAlliances() {
    return {
      qiip: {
        name: "qiip",
        id: 56,
        sku: "AS10K0521",
        image: "https://c4uno-panel.s3.amazonaws.com/alliances/logo/qiip.png",
        description:
          "qiip y Bamba unen sus fuerzas para ofrecerte servicios financieros y de protección, ayudándote a resolver imprevistos médicos 10 veces más rápido y 10 veces más económico",
        address: {
          colony: "Actipan",
          external_number: "1428",
          internal_number: "",
          municipality: "Benito Juárez",
          state: "Ciudad de México",
          state_id: 1,
          street: "Av. Insurgentes Sur",
          town: "Ciudad de México",
          zip_code: "03230",
        },
        coupon: "QIIP20",
      },
      solvo: {
        name: "solvo",
        id: 56,
        sku: "AS10K0521",
        image: "https://c4uno-panel.s3.amazonaws.com/alliances/logo/solvo.png",
        description:
          "Solvo y Bamba unen sus fuerzas para ofrecerte servicios financieros y de protección, ayudándote a resolver imprevistos médicos 10 veces más rápido y 10 veces más económico",
        address: {
          colony: "Actipan",
          external_number: "1428",
          internal_number: "",
          municipality: "Benito Juárez",
          state: "Ciudad de México",
          state_id: 1,
          street: "Av. Insurgentes Sur",
          town: "Ciudad de México",
          zip_code: "03230",
        },
        coupon: "SOLVO20",
      },
      alphacredit: {
        name: "alphacredit",
        id: 56,
        sku: "AS10K0521",
        image:
          "https://c4uno-panel.s3.amazonaws.com/alliances/logo/alphacredit.png",
        description:
          "Alphacredit y Bamba unen sus fuerzas para ofrecerte servicios financieros y de protección, ayudándote a resolver imprevistos médicos 10 veces más rápido y 10 veces más económico",
        address: {
          colony: "Actipan",
          external_number: "1428",
          internal_number: "",
          municipality: "Benito Juárez",
          state: "Ciudad de México",
          state_id: 1,
          street: "Av. Insurgentes Sur",
          town: "Ciudad de México",
          zip_code: "03230",
        },
        coupon: "ALPHA20",
      },
      runa: {
        name: "runa",
        id: 56,
        sku: "AS10K0521",
        image: "https://c4uno-panel.s3.amazonaws.com/alliances/logo/runa.png",
        description:
          "Runa y Bamba unen sus fuerzas para ofrecerte servicios financieros y de protección, ayudándote a resolver imprevistos médicos 10 veces más rápido y 10 veces más económico",
        address: {
          colony: "Actipan",
          external_number: "1428",
          internal_number: "",
          municipality: "Benito Juárez",
          state: "Ciudad de México",
          state_id: 1,
          street: "Av. Insurgentes Sur",
          town: "Ciudad de México",
          zip_code: "03230",
        },
        coupon: "RUNA20",
      },
      treo: {
        name: "treo",
        id: 56,
        sku: "AS10K0521",
        image: "https://c4uno-panel.s3.amazonaws.com/alliances/logo/treo.png",
        description:
          "Treo y Bamba unen sus fuerzas para ofrecerte servicios financieros y de protección, ayudándote a resolver imprevistos médicos 10 veces más rápido y 10 veces más económico",
        address: {
          colony: "Actipan",
          external_number: "1428",
          internal_number: "",
          municipality: "Benito Juárez",
          state: "Ciudad de México",
          state_id: 1,
          street: "Av. Insurgentes Sur",
          town: "Ciudad de México",
          zip_code: "03230",
        },
        coupon: "TREO20",
      },
      municipioags: {
        name: "municipioags",
        id: 56,
        sku: "AS10K0521",
        image:
          "https://c4uno-panel.s3.amazonaws.com/alliances/logo/municipioags.png",
        description:
          "Municipio de Aguascalientes, Treo  y Bamba unen sus fuerzas para ofrecerte servicios financieros y de protección, ayudándote a resolver imprevistos médicos 10 veces más rápido y 10 veces más económico",
        address: {
          colony: "Actipan",
          external_number: "1428",
          internal_number: "",
          municipality: "Benito Juárez",
          state: "Ciudad de México",
          state_id: 1,
          street: "Av. Insurgentes Sur",
          town: "Ciudad de México",
          zip_code: "03230",
        },
        coupon: "AGS20",
      },
      netfe: {
        name: "netfe",
        id: 56,
        sku: "AS10K0521",
        image: "https://c4uno-panel.s3.amazonaws.com/alliances/logo/netfe.png",
        description:
          "Netfe y Bamba unen sus fuerzas para ofrecerte servicios financieros y de protección, ayudándote a resolver imprevistos médicos 10 veces más rápido y 10 veces más económico",
        address: {
          colony: "Actipan",
          external_number: "1428",
          internal_number: "",
          municipality: "Benito Juárez",
          state: "Ciudad de México",
          state_id: 1,
          street: "Av. Insurgentes Sur",
          town: "Ciudad de México",
          zip_code: "03230",
        },
        coupon: "NETFE20",
      },
      cornershop: {
        name: "cornershop",
        id: 56,
        sku: "AS10K0521",
        image:
          "https://c4uno-panel.s3.amazonaws.com/alliances/logo/cornershop.png",
        description:
          "Cornershop y Bamba unen sus fuerzas para ofrecerte servicios financieros y de protección, ayudándote a resolver imprevistos médicos 10 veces más rápido y 10 veces más económico",
        address: {
          colony: "Actipan",
          external_number: "1428",
          internal_number: "",
          municipality: "Benito Juárez",
          state: "Ciudad de México",
          state_id: 1,
          street: "Av. Insurgentes Sur",
          town: "Ciudad de México",
          zip_code: "03230",
        },
        coupon: "CORNERSHOP20",
      },
      crediamigo: {
        name: "crediamigo",
        id: 56,
        sku: "AS10K0521",
        image:
          "https://c4uno-panel.s3.amazonaws.com/alliances/logo/crediamigo.png",
        description:
          "Crediamigo y Bamba unen sus fuerzas para ofrecerte servicios financieros y de protección, ayudándote a resolver imprevistos médicos 10 veces más rápido y 10 veces más económico",
        address: {
          colony: "Actipan",
          external_number: "1428",
          internal_number: "",
          municipality: "Benito Juárez",
          state: "Ciudad de México",
          state_id: 1,
          street: "Av. Insurgentes Sur",
          town: "Ciudad de México",
          zip_code: "03230",
        },
        coupon: "CREDIAMIGO20",
      },
      doraldent: {
        name: "doraldent",
        id: 56,
        sku: "AS10K0521",
        image:
          "https://c4uno-panel.s3.amazonaws.com/alliances/logo/doraldent.png",
        description:
          "Doraldent y Bamba unen sus fuerzas para ofrecerte servicios financieros y de protección, ayudándote a resolver imprevistos médicos 10 veces más rápido y 10 veces más económico",
        address: {
          colony: "Actipan",
          external_number: "1428",
          internal_number: "",
          municipality: "Benito Juárez",
          state: "Ciudad de México",
          state_id: 1,
          street: "Av. Insurgentes Sur",
          town: "Ciudad de México",
          zip_code: "03230",
        },
        coupon: "DORALDENT20",
      },
    };
  },
};
